### ISSUE TITLE
When serving a project with vite, loadParquet fails if i don't provide a fully qualified url

### ISSUE THREAD

**Issue by kszlim** [uwdata/mosaic#636]
Repro:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script type="module" defer>
        import * as vg from "@uwdata/vgplot";

        vg.coordinator().databaseConnector(vg.wasmConnector());

        vg.coordinator().exec(vg.loadParquet("penguins", "/data/some_parquet.parquet")); // stored in public/data/some_parquet.parquet

        const chart = vg.plot(
            vg.hexbin(vg.from("penguins"), { x: "col_0", y: "col_2" })
        );

        document.getElementById('chart-container').appendChild(chart);
    </script>
</head>
<body>
    <div id="chart-container"></div>
</body>
```

Then i run:
```
npm start
```

Which is defined as:
`"start": "vite"`

I get the error:
```
Error: IO Error: No files found that match the pattern "/data/some_parquet.parquet"
    at ma.runQuery (bindings_base.ts:172:19)
    at Fo.onMessage (worker_dispatcher.ts:202:51)
    at Wc.globalThis.onmessage (duckdb-browser-eh.worker.ts:29:19)
```

whereas it seems to work if I provide something like:

```
vg.coordinator().exec(vg.loadParquet("penguins", "http://localhost:MY_PORT/data/some_parquet.parquet"));
```

**Comment by declann** [comment]
The higher level [`astToESM` function](https://idl.uw.edu/mosaic/api/spec/parser-generators.html#asttoesm) takes a `baseURL` that it bakes into the loadParquet calls.

The default Mosaic app in [dev folder](https://github.com/uwdata/mosaic/tree/main/dev) - which is a vite app, sets baseURL using `location.origin + '/'` : is pre-pending that ok?

https://vscode.dev/github/uwdata/mosaic/blob/main/dev/index.html#L194
